# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='Comment')),
                ('date', models.DateField(verbose_name='Commented on')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['date'],
                'verbose_name': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='facepad_app.Comment', verbose_name='Comment')),
            ],
            options={
                'verbose_name_plural': 'Likes',
                'verbose_name': 'Like',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Message content')),
                ('date', models.DateField(verbose_name='Message date')),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ['date'],
                'verbose_name': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Post content')),
                ('date', models.DateField(verbose_name='Posted on')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['date'],
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section name')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_section', to='facepad_app.Section')),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'verbose_name': 'Section',
            },
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('avatar', models.ImageField(upload_to='/avatars/', verbose_name='Avatar')),
                ('date', models.DateField(verbose_name='Date of birth')),
                ('friend', models.ManyToManyField(related_name='related_friends', to='facepad_app.SimpleUser', verbose_name='Friends')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['name', 'date'],
                'verbose_name': 'User',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='facepad_app.Section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='facepad_app.SimpleUser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiverUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageReceiver', to='facepad_app.SimpleUser', verbose_name='Receiver'),
        ),
        migrations.AddField(
            model_name='message',
            name='senderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageSender', to='facepad_app.SimpleUser', verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='facepad_app.Post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='facepad_app.SimpleUser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='facepad_app.Post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='facepad_app.SimpleUser', verbose_name='User'),
        ),
    ]
