# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facepad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_friends', to='facepad_app.SimpleUser', verbose_name='Friends'),
        ),
    ]
