# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facepad_app', '0002_auto_20160321_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_section', to='facepad_app.Section'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='avatar',
            field=models.ImageField(upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
