# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facepad_app', '0003_auto_20160321_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='facepad_app.Comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='facepad_app.Post', verbose_name='Post'),
        ),
    ]
