# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facepad_app', '0004_auto_20160321_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
